baseURL = 'https://wenchin77.github.io'
metaDataFormat = "yaml"
title = "在地球上迷了路"
theme = "blist"
googleAnalytics = 'G-2H09ZZ2TDE'

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en] # 使用英文 config
    contentDir = "content/zh" # 中文
    weight = 1
    languageName = "中文"
    title = "在地球上迷了路"
    [languages.en.params]
      introTitle = "在地球上迷了路"
      introSubtitle = "天涯海角的流浪與覺醒"
      introPhoto = "/home_picture.png"
    [[languages.en.menu.main]]
        name = "文章"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "關於"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Wenchin · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "IG 追蹤 lost.on.earth.journey，讀最新的故事！"
  # twitter = "https://twitter.com/"
  # linkedin = "https://linkedin.com/in/"
  # github = "https://github.com/"
  # medium = "https://medium.com/"
  # reddit = "https://reddit.com/"
  # dribbble = "https://dribbble.com/"
  instagram="https://www.instagram.com/lost.on.earth.journey/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
